apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  name: pyflink-hello-world
spec:
  image: viet1846/flink-app:v1
  flinkVersion: v1_18
  flinkConfiguration:
    taskmanager.numberOfTaskSlots: "1"
  serviceAccount: flink
  jobManager:
    resource:
      memory: "1024m"
      cpu: 1
  taskManager:
    resource:
      memory: "1024m"
      cpu: 1
  podTemplate:
    spec:
      containers:
        - name: flink-main-container
          env:
            - name: AWS_ACCESS_KEY_ID
              value: "admin"
            - name: AWS_SECRET_ACCESS_KEY
              value: "password"
            - name: AWS_REGION
              value: "us-east-1"
            - name: AWS_DEFAULT_REGION
              value: "us-east-1"
            - name: S3_ENDPOINT
              value: "http://minio.minio.svc.cluster.local:9000"
            - name: S3_PATH_STYLE_ACCESS
              value: "true"
  job:
    jarURI: local:///opt/flink/opt/flink-python-1.18.1.jar
    entryClass: "org.apache.flink.client.python.PythonDriver"
    args:
      [
        "-pyclientexec",
        "/usr/bin/python3",
        "-py",
        "/app/pyflink_hello_world.py",
      ]
    parallelism: 1
    upgradeMode: stateless
